### ISSUE TITLE
give me error. :(

### ISSUE THREAD

**Issue by davuttemel** [ohidurbappy/python-flask-on-cpanel#1]
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'api/requirements.txt'[notice] A new release of pip is available: 23.0 -> 24.0[notice] To update, run: pip install --upgrade pip

**Comment by ohidurbappy** [comment]
Check the path. May be the wrong path provided.

**Comment by davuttemel** [comment]
A few min later  is working fine.  :) thank you.
